name: Check IPTV Valid Streams

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨 11AM MYT 执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download IPTV List
        run: python iptv_downloader.py

      - name: Check and Classify Streams
        run: python iptv_checker.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add valid_my/
          git commit -m "Update valid streams" || echo "No changes"
          git push
