name: Check IPTV Valid Streams

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨 3:00 UTC（11AM MYT）执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download IPTV List
        run: python iptv_downloader.py

      - name: Check and Classify Streams
        run: python iptv_checker.py

      - name: Commit results
        run: |
          # 开启严格模式
          set -eux
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update valid streams"
            git push
          else
            echo "✅ No changes to commit"
          fi
